### ISSUE TITLE
BunsenLabs Hydrogen: Numeric release ID

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-os-release#1]
lsb_release (most common info system, present on both systemd and sysvinit systems) and os-release (born from systemd, present in Jessie) specify, besides a release name, a numeric version or version ID.

I suggest that in Hydrogen, we set this version ID to 8 and and track future Debian release numbers.

**Comment by johnraff** [comment]
Sounds reasonable.

**Comment by ghost** [comment]
No particular objections; closing.
