### ISSUE TITLE
Calendar Dropdown No Longer Working

### ISSUE THREAD

**Issue by DrKondor** [BunsenLabs/bunsen-os-release#4]

**Comment by capn-damo** [comment]
I don't think this has any relevance to bunsen-os-release, and probably has nothing to do with any of the other BL github repos either.

I'm guessing this is an issue with a BunsenLabs installation, so the best place for posting bugs or problems is on the forums' BL Development section: http://crunchbang.org/forums/viewforum.php?id=21
