### ISSUE TITLE
Some install scripts choking on release name "Hydrogen"

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-os-release#5]
This BunsenLabs forum issue:
https://forums.bunsenlabs.org/viewtopic.php?pid=7194#p7194
is about installation of nodesource.js
While we can't be held resposible for third-party scripts, neither can be demand that everyone include "Hydrogen" in their lists of supported distributions...

Is there not an argument for reverting to "Jessie"?

**Comment by ghost** [comment]
Well, the system would show up in grub not as BunsenLabs but Debian Jessie. Even if we would place a special grub config, if the user multiboots and let's another OS manage the bootloader, this would happen.

System identification for our purposes (or, for example, screenfetch) we could do another (even maybe non-standard) way.

I don't mind.

Perhaps the boot prompt is the main issue; if the user has Debian Jessie (vanilla) and Debian Jessie (BunsenLabs) installed, you need to look hard at the bootprompt and determine which to boot. A non-issue for me, a big issue for beginners, I could imagine.

**Comment by johnraff** [comment]
> if the user has Debian Jessie (vanilla) and Debian Jessie (BunsenLabs) installed, you need to look hard at the bootprompt and determine which to boot. A non-issue for me, a big issue for beginners, I could imagine.

True.
Maybe we could just post a HOWTO on the forum explaining the issues that might arise and suggesting they uninstall **bunsen-os-release** if it causes such problems.

**Comment by ghost** [comment]
This is now explained in bunsen-os-release(5).
