### ISSUE TITLE
Change codename to bunsen-hydrogen?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-os-release#6]
[BunsenLabs forum post](https://forums.bunsenlabs.org/viewtopic.php?pid=12577#p12577)

If line 4 of lsb-release.bunsen is changed to 

```
DISTRIB_CODENAME="bunsen-hydrogen"
```

then some of the issues that occurred with python-apt seem to be resolved.
Would this be acceptable?

**Comment by capn-damo** [comment]
Doesn't matter to me really, as long as the name is adequately descriptive.

**Comment by ghost** [comment]
What entry does GRUB use when generating the boot menu description? Does it still say "BunsenLabs GNU/Linux 8.2 (Hydrogen)" after regenerating the menu with the improved setting?

If that turns out fine, I'll  change the codename to bunsen-hydrogen.

**Comment by johnraff** [comment]
It says **BunsenLabs GNU/Linux**.
I don't think it ever said "BunsenLabs GNU/Linux 8.2 (Hydrogen)" to be honest.

---

...check: same result regardless of change in DISTRIB_CODENAME (`sudo update-grub` in between).

...further check: 

/etc/default/grub:line 8:

```
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
```

( `lsb_release -i -s` returns the DISTRIB_ID ie "BunsenLabs".)

/etc/grub.d/10_linux:from line 37:

```
if [ "x${GRUB_DISTRIBUTOR}" = "x" ] ; then
  OS=GNU/Linux
else
  case ${GRUB_DISTRIBUTOR} in
    Ubuntu|Kubuntu)
      OS="${GRUB_DISTRIBUTOR}"
      ;;
    *)
      OS="${GRUB_DISTRIBUTOR} GNU/Linux"
      ;;
  esac
  CLASS="--class $(echo ${GRUB_DISTRIBUTOR} | tr 'A-Z' 'a-z' | cut -d' ' -f1|LC_ALL=C sed 's,[^[:alnum:]_],_,g') ${CLASS}"
fi
```

$OS is then used to generate the menu entry, so it doesn't seem to use the codename or description at all.

...and Happy Christmas!

**Comment by ghost** [comment]
Cool. So I'll make the change and push the package some time down the road.

And happy end-of-the-year holidays to you too! Though apparently w/o snow around here this year [there was a nice snowfall in 2013/14].
